<?php
    get_template_part('template-parts/components/home/element','featured');
    get_template_part('template-parts/components/home/element','streaming');
    get_template_part('template-parts/components/home/element','tournament');
?>
<div>
    <?php
        get_template_part('template-parts/components/home/element','news');
    ?>
</div>